default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

logger:
  logs:
    custom_components.hacs: debug
    aiogithubapi: debug

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
